apiVersion: v1
kind: Pod
metadata:
  name: nodejs-helloworld
  labels:
    app: nodejs-helloworld
spec:
  containers:
    - name: k8s-demo
      image: demoapp:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000