apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: demoapp:2
        imagePullPolicy: Never
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - name: db-secret-volume
          mountPath: /etc/creds
          readOnly: true
     
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 5
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 6
          timeoutSeconds: 30
      nodeSelector:
        name: node1
      volumes:
      - name: db-secret-volume
        secret:
          secretName: db-secret
      
          